"""BacktestReport + markdown / JSON renderers.

Markdown output format mirrors `docs/backtests/<class>_90d.md` from the
strategy SDK so allocator authors can drop a generated report into
`docs/allocators/<name>_90d.md` without reformatting.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from dataclasses import asdict, dataclass, field


@dataclass(frozen=True, slots=True)
class BacktestReport:
    allocator_name: str
    capital: int
    period: str
    period_days: int
    final_nav: float
    total_return: float
    sharpe: float
    max_drawdown: float
    allocator_fees_paid: float
    daily_nav: Sequence[float]
    decisions: Sequence[dict[str, float]]
    fills_by_strategy: dict[str, int] = field(default_factory=dict)

    def summary_dict(self) -> dict[str, float | int | str]:
        return {
            "allocator_name": self.allocator_name,
            "capital": self.capital,
            "period": self.period,
            "period_days": self.period_days,
            "final_nav": round(self.final_nav, 2),
            "total_return_pct": round(self.total_return * 100, 4),
            "sharpe": round(self.sharpe, 4),
            "max_drawdown_pct": round(self.max_drawdown * 100, 4),
            "allocator_fees_paid": round(self.allocator_fees_paid, 2),
        }


def render_json(report: BacktestReport, *, pretty: bool = True) -> str:
    """Full report including the daily NAV path and per-day decisions."""
    payload = asdict(report)
    payload["daily_nav"] = [round(v, 4) for v in report.daily_nav]
    payload["decisions"] = [
        {k: round(v, 4) if isinstance(v, float) else v for k, v in d.items()}
        for d in report.decisions
    ]
    if pretty:
        return json.dumps(payload, indent=2, sort_keys=True)
    return json.dumps(payload, sort_keys=True)


def render_markdown(report: BacktestReport) -> str:
    """Mirror of `docs/backtests/<class>_90d.md` shape."""
    s = report.summary_dict()
    lines = [
        f"# Backtest — `{report.allocator_name}` ({report.period}, allocator-sdk)",
        "",
        "Generated by `helios_allocator.backtest.run_backtest`.",
        "",
        "## Headline numbers",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Starting capital | ${report.capital:,} |",
        f"| Final NAV | ${s['final_nav']:,.2f} |",
        f"| Total return | {s['total_return_pct']:+.2f}% |",
        f"| Sharpe (annualised) | {s['sharpe']:+.2f} |",
        f"| Max drawdown | {s['max_drawdown_pct']:.2f}% |",
        f"| Allocator fees paid | ${s['allocator_fees_paid']:,.2f} |",
        f"| Period | {report.period} ({report.period_days} days) |",
        "",
        "## Per-strategy fill counts",
        "",
        "| Strategy | Days held |",
        "|---|---:|",
    ]
    for sid, fills in sorted(report.fills_by_strategy.items(), key=lambda kv: -kv[1]):
        lines.append(f"| `{sid}` | {fills} |")
    lines += [
        "",
        "## Caveats",
        "",
        "- The harness runs against *historical* strategy NAV traces; it does",
        "  not re-simulate strategy-internal alpha. Allocator quality is the",
        "  variable under test, not strategy alpha.",
        "- Allocator fees crystallise on each HWM cross above the configured",
        "  threshold (default 5%). Compare like-for-like before reading too",
        "  much into the fee column.",
        "- See `Helios.md §11.3` for the SDK contract and `docs/reputation-",
        "  math.md` for how realised performance feeds the allocator's own",
        "  reputation score.",
    ]
    return "\n".join(lines) + "\n"


__all__ = ["BacktestReport", "render_json", "render_markdown"]
