// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @title ClassIds
/// @notice Canonical strategy-class identifiers, pinned as `bytes32` constants
///         that fit inside the BN254 scalar field.
///
///         The Groth16 verifiers generated by snarkjs run a `checkField` over
///         every public signal and revert when any signal is ≥ the field
///         modulus `r ≈ 2^254`. The natural-feeling `keccak256("momentum_v1")`
///         convention produces digests above that bound for all three Phase
///         2 classes, which makes real proofs un-acceptable on-chain.
///         Encoding the class identifier as a Poseidon hash keeps it inside
///         the field by construction (Poseidon's output range is `[0, r)`).
///
///         Convention: `id = Poseidon([int.from_bytes(<name>, "big")])`,
///         where `<name>` is the ASCII slug (e.g. `b"momentum_v1"`). Slugs
///         must be ≤ 31 bytes so the integer interpretation fits the field.
///         The values below are the result of running the canonical
///         `circomlibjs.buildPoseidon()` against that input — re-derive them
///         via `services/oracle/src/oracle/poseidon.py::poseidon_hash` and
///         the Foundry test `ClassIds.t.sol` re-asserts the equality on
///         every `forge test` run via `vm.ffi`.
///
///         Helios.md §6.2 / §9.
library ClassIds {
    /// @notice `Poseidon([int.from_bytes(b"momentum_v1", "big")])`
    bytes32 internal constant MOMENTUM_V1 =
        0x2a9aa442064b635baec37a7a259282faa5563a653a8325378d5676c6f04bc9dd;

    /// @notice `Poseidon([int.from_bytes(b"mean_reversion_v1", "big")])`
    bytes32 internal constant MEAN_REVERSION_V1 =
        0x18602f4f74172d545f5258541634e1a125c3a4e1227ee2a4cbee957d3490f1fb;

    /// @notice `Poseidon([int.from_bytes(b"yield_rotation_v1", "big")])`
    bytes32 internal constant YIELD_ROTATION_V1 =
        0x2e882135c6afc3bda02a9c8a7c6a351198d97599c804a2575a3d616073a87251;
}
